version: '3.8'

volumes:
  datafiles:

services:
  database:
    #Pull the latest mysql image
    image: mysql:8.0.26
    ports:
      - "3307:3306"
    restart: always
    #Specify Environment Variables for mysql
    environment: 
      MYSQL_ROOT_PASSWORD: milkyway97
      MYSQL_USER: username
      MYSQL_PASSWORD: 1111
      MYSQL_DATABASE: testdb
  api:
    build:
      context: .
      #Use the DockerFile in that Directory
      dockerfile: Dockerfile
    depends_on: 
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development